# https://www.parlament.ch/de/organe/fraktionen/im-parlament-vertretene-parteien

languages: ["de","fr","it","en"]
parties:
    - website: "https://www.fdp.ch"
      twitter: "FDP_Liberalen"
      abbrs: ["FDP","PLR"]
      name:
        de: "FDP.Die Liberalen"
        fr: "Les Liberaux-Radicaux"
        it: "I Liberali"
        en: "The Liberals"
    - website: "https://www.svp.ch"
      twitter: "SVPch"
      abbrs: ["SVP","UDC"]
      name:
        de: "Schweizerische Voklspartei"
        fr: "Union Démocratique du Centre"
        it: "Unione Democratica Di Centro"
        en: "Swiss Peoples Party"
    - website: "https://www.bdp.info"
      twitter: "bdpschweiz"
      abbrs: ["BDP","PBD"]
      name:
        de: "Bürgerlich Demokratische Partei"
        fr: "Parti Bourgeois-Démoratique"
        it: "Partito Borghese Democratico"
        en: "Liberal Democartic Party"
    - website: "www.cvp.ch"
      twitter: "CVP_PDC"
      abbrs: ["CVP","PDC"]
      name:
        de: "Christlichdemokratische Volkspartei"
        fr: "Parti Démocrate-Chrétien"
        it: "Partito Popolare Democratico"
        en: "Christian Democrats"
    - website: "https://www.evppev.ch"
      twitter: "evppev"
      abbrs: ["EVP","PEV"]
      name:
        de: "Evangelische Volkspartei der Schweiz"
        fr: "Parti Evangélique Suisse"
        it: "Partito Evangelico Svizzero"
        en: "Evangelical People's Party"
    - website: "https://www.gruene.ch/"
      twitter: "GrueneCH"
      abbrs: ["GPS", "PES"]
      name:
        de: "Die Grünen"
        fr: "Les Verts"
        it: "Partito Ecologista Svizzero - I Verdi"
        en: "Green Party"
    - website: "https://grunliberale.ch/"
      twitter: "grunliberale"
      abbrs: ["GLP", "PVL"]
      name:
        de: "Grünliberale"
        fr: "Parti Vert'Liberale"
        it: "Partito Verde-Librale"
        en: "Green Liberal"
    - website: "http://www.mcge.ch/"
      twitter: ""
      abbrs: ["MCG"]
      name:
        de: "Mouvement Citoyens Genevois"
        fr: "Mouvement Citoyens Genevois"
        it: "Mouvement Citoyens Genevois"
        en: "Mouvement Citoyens Genevois"
    - website: "https://pda.ch/"
      twitter: ""
      abbrs: ["PDA","PST"]
      name:
        de: "Partei der Arbeit der Schweiz"
        fr: "Parti Susisse de Travail"
        it: "Partito Operaio e Popolare Pop"
        en: "Partei der Arbeit der Schweiz"
    - website: "http://www.lega-dei-ticinesi.ch/"
      twitter: ""
      abbrs: ["LEGA"]
      name:
        de: "Lega di Ticinesi"
        fr: "Lega di Ticinesi"
        it: "Lega di Ticinesi"
        en: "Lega di Ticinesi"
    - website: "https://www.sp-ps.ch"
      twitter: "spschweiz"
      abbrs: ["SP","PS"]
      name:
        de: "Sozialdemokratische Partei"
        fr: "Parti Socialiste"
        it: "Partito Socialista"
        en: "Social Democrats"