twitterListAccount: "SoMePolis"
twitterListName: "BundesparlamentarierInnen"
# https://www.parlament.ch/de/organe/fraktionen/im-parlament-vertretene-parteien
parties:
    - twitter: "spschweiz"
      abbrs: ["SP","PS"]
      keywords: ["socialist", "sozialist"]
    - twitter: "FDP_Liberalen"
      abbrs: ["FDP","PLR"]
      keywords: ["fdp","plr"]
    - twitter: "SVPch"
      abbrs: ["SVP","UDC"]
      keywords: ["svp","udc"]
    - twitter: "bdpschweiz"
      abbrs: ["BDP","PBD"]
      keywords: ["bdp","pbd"]
    - twitter: "CVP_PDC"
      abbrs: ["CVP","PDC"]
      keywords: ["cvp","pdc"]
    - twitter: "evppev"
      abbrs: ["EVP","PEV"]
      keywords: ["evp","pev"]
    - twitter: "GrueneCH"
      abbrs: ["GPS", "PES"]
      keywords: ["gp","pes","grüne","gruene"]
    - twitter: "grunliberale"
      abbrs: ["GLP", "PVL"]
      keywords: ["glp","pvl"]
    - twitter: ""
      abbrs: ["MCG"]
      keywords: ["mcg"]
    - twitter: ""
      abbrs: ["PDA","PST"]
      keywords: ["pda","pst"]
    - twitter: ""
      abbrs: ["LEGA"]
      keywords: ["lega"]